swagger: '2.0'
info:
  version: 0.0.1
  title: DataMiningCloud Engine Dispacther
  description: An API specification of DMC Dispacther based on swagger-2.0 specification
  contact:
    name: Aid
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /engine_dispatcher/
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:

  /processes:
    post:
      tags:
      - processes
      summary: Create a new process.
      description: Dispacther will dispatch process event to the agent.
      responses:
        202:
          description: OK

  /processes/{key}:
    get:
      tags:
      - processes
      sumary: Check the status of processes
      responses:
        200:
          description: OK

  /processes/{key}/{subProcessKey}:
    post:
      tags:
      - processes
      summary: When a agent finished a process, call this API as a completed handler, the dispatch will dispatch next agent if needed.
      responses:
        202:
          description: OK

definitions:
  Domain:
    properties:
      name:
        type: string
      date:
        description: The domain in differnent date may different, think about the change of computer brand from 1995 to 2015 .
        type: string
      parentDomain:
        $ref: '#/definitions/Domain'

  DMData:
    properties:
      key:
        type: string
      data:
        type: array
        items:
         $ref: '#/definitions/ColumnData'

  ColumnData:
    properties:
      attribute:
        $ref: '#/definitions/Attribute'
      data:
        type: array
        items:
          type: string

  DataInfor:
    properties:
      name:
        type: string
      domain:
        $ref: '#/definitions/Domain'

  Attribute:
    properties:
      name:
        type: string
      type:
        type: string
      format:
        type: string
      dataInfor:
        $ref: '#/definitions/DataInfor'

  EvaluationData:
    properties:
      data:
        $ref: '#/definitions/DMData'
      resultAttr:
        $ref: '#/definitions/Attribute'

  TrainerEvaluationData:
    properties:
      data:
        $ref: '#/definitions/DMData'
      resultAttr:
        $ref: '#/definitions/Attribute'
      crossNumber:
        type: integer

  ServiceEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string

  ServiceEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/ServiceEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: '#/definitions/DMData'

  TrainerEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string
      evaType:
        description: 10-crosses evaluation? or n-crosses?
        type: string

  TrainerEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/TrainerEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: '#/definitions/DMData'
