swagger: '2.0'
info:
  version: 0.0.1
  title: Engine Task Dispacther
  description: An API specification of DMC Dispacther based on swagger-2.0 specification
  contact:
    name: Aid
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /engine_dispatcher/
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:

  /slots/{key}:
    get:
      tags:
      - slots
      parameters:
      - name: key
        in: path
        type: string
      sumary: Check the status of slots
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TaskEvent'


  /slots/{key}:
    post:
      tags:
      - slots
      parameters:
      - name: key
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/TaskEvent'
      description: When a agent finished a process, call this API as a completed handler, the dispatch will dispatch next agent if needed.
      responses:
        204:
          description: OK

definitions:
  Domain:
    properties:
      name:
        type: string
      date:
        description: The domain in differnent date may different, think about the change of computer brand from 1995 to 2015 .
        type: string
      parentDomain:
        $ref: '#/definitions/Domain'

  DMData:
    properties:
      key:
        type: string
      data:
        type: array
        items:
         $ref: '#/definitions/ColumnData'

  ColumnData:
    properties:
      attribute:
        $ref: '#/definitions/Attribute'
      data:
        type: array
        items:
          type: string

  DataInfor:
    properties:
      name:
        type: string
      domain:
        $ref: '#/definitions/Domain'

  Attribute:
    properties:
      name:
        type: string
      type:
        type: string
      format:
        type: string
      dataInfor:
        $ref: '#/definitions/DataInfor'

  TaskEvent:
    properties:
      _id:
        type: string
      datetime:
        type: string
      status:
        type: string
      data:
        $ref: '#/definitions/DMData'
